image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.43.0
agentCollector:
  enabled: false
standaloneCollector:
  enabled: true
  extraEnvs:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: otel-datadog-secrets
          key: DD_API_KEY
  configOverride:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    extensions:
      health_check: {}
    exporters:
      datadog/api:
        env: development
        version: 0.43.0
        tags:
          - source:develop-green-otel
        api:
          key: "$DD_API_KEY"
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [datadog/api]
