name: Quality Gate
env:
  COVERAGE_THRESH_PCT: 0

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  ci_gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Setup unit test
        run: go install github.com/klmitch/overcover@v1.2.1
      - name: Build check
        run: go build
      - name: Run unit test with coverage
        run: go test --coverprofile cover.out ./...
      - name: Check coverage meets threshold
        run: overcover --coverprofile cover.out ./... --threshold ${{ env.COVERAGE_THRESH_PCT }}
